import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

import Colors from '../../Colors';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  image: {
    flex: 1,
    justifyContent: 'center',
    // alignItems: 'center',
    // paddingVertical: wp(24),
  },
  innercontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: wp(10),
  },
  viewref: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(10),
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.blue,
    alignSelf: 'flex-end',
    top: wp(4),
    right: wp(4),
  },
  ref: {
    width: wp(6),
    height: wp(6),
  },
  timerview: {
    width: wp(90),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    marginTop: wp(2),
  },
  inputstyl: {
    backgroundColor: Colors.white,
    width: wp(90),
    height: wp(40),
    borderRadius: wp(6),
    paddingHorizontal: wp(2),
    paddingVertical: wp(2),
  },
  Videoview: {
    backgroundColor: Colors.transperentheader,
    width: wp(95),
    height: wp(60),
    alignItems: 'center',
    alignSelf: 'center',
    // borderRadius: wp(2),
    // elevation: 2,
    // shadowColor: '#000000',
    // shadowOffset: {
    //   width: 0,
    //   height: 0.5,
    // },
    // shadowRadius: 1,
    // shadowOpacity: 0.5,
  },
  reddot: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(5),
    backgroundColor: Colors.red,
    elevation: 2,
    shadowColor: Colors.red,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  texrec: {
    marginLeft: wp(2),
    fontSize: 14,
    fontWeight: '600',
    color: Colors.white,
  },
  imaginner: {
    width: wp(3),
    height: wp(3),
  },
  donttextor: {
    fontSize: 14,
    fontWeight: '400',
    color: Colors.black,
  },
  linview: {
    width: wp(40),
    backgroundColor: Colors.gray,
    height: 1,
  },
  uplodvideo: {
    borderStyle: 'dashed',
    borderWidth: 1,
    borderRadius: 1,
    borderColor: Colors.blue,
    width: wp(87),
    height: wp(37),
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgup: {
    width: wp(10),
    height: wp(10),
  },
  textup: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: '600',
    marginTop: wp(2),
  },
  orview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp(90),
    marginTop: wp(5),
    alignSelf: 'center',
  },
  recodmenuview: {
    backgroundColor: Colors.transperentheader,
    height: wp(46),
    width: wp(92),
  },
  recodmenuview23: {
    backgroundColor: Colors.transperentheader,
    height: wp(48),
    width: wp(92),
    marginTop: wp(2),
    marginBottom: wp(4),
  },
  recoptin: {
    flexDirection: 'row',
    width: wp(90),
    height: wp(12),
    // backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(3),
  },
  imaginner1: {
    width: wp(5),
    height: wp(5),
  },
  thumbimg: {
    height: wp(46),
    width: wp(92),
    borderBottomColor: Colors.red,
    borderBottomWidth: 3,
  },
  textouch: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: '600',
  },
  touchtag: {
    width: wp(90),
    backgroundColor: Colors.white,
    elevation: 2,
    height: wp(8),
    justifyContent: 'center',
    paddingHorizontal: wp(2),
  },
  flatlisviewlist: {
    width: wp(90),
    alignItems: 'center',
    justifyContent: 'center',

    alignSelf: 'center',
    paddingHorizontal: wp(1),
    paddingVertical: wp(2),
  },
  text: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: '600',
    alignSelf: 'center',
    marginTop: wp(3),
    // height: wp(8),
    textAlign: 'center',
  },
  hedview: {
    backgroundColor: Colors.transperentheader,
    width: wp(90),
    height: wp(7),
    marginTop: wp(0),
    justifyContent: 'center',
  },
  liveview: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(9),
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.transperent,
  },
  temodal: {
    fontSize: 12,
    color: Colors.black,
    fontWeight: '600',
  },
  temodal1: {
    fontSize: 10,
    color: Colors.black,
    fontWeight: '400',
  },
  touchmodalbu: {
    backgroundColor: Colors.black,
    width: wp(14),
    alignItems: 'center',
    justifyContent: 'center',
    height: wp(6),
    borderRadius: wp(3),
  },
  viewmobu: {
    flexDirection: 'row',
    width: wp(33),
    marginTop: wp(4),
    justifyContent: 'space-between',
    paddingHorizontal: wp(2),
  },
  textmo: {
    fontSize: 12,
    color: Colors.white,
    fontWeight: '600',
  },
  textmo1: {
    fontSize: 12,
    color: Colors.black,
    fontWeight: '600',
  },
  touchmodalbu1: {
    borderColor: Colors.black,
    backgroundColor: Colors.white,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(14),
    height: wp(6),
    borderRadius: wp(3),
  },
  confmodal: {
    width: wp(70),
    height: wp(24),
    alignSelf: 'center',
    top: wp(55),
    paddingHorizontal: wp(4),
    paddingVertical: wp(4),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  asklivtxt: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.white,
  },
  buttonview: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: wp(90),
    paddingHorizontal: wp(2),
  },
  coverrstyl: {
    width: wp(20),
    height: wp(11),
    borderRadius: wp(1),
  },
  coverrstyl12: {
    width: wp(22),
    height: wp(12),
    borderRadius: wp(1),

    alignItems: 'center',
    justifyContent: 'center',
  },
  flatviecover: {
    width: wp(90),
    height: wp(14),
    alignSelf: 'center',
  },
  coverrstylspace: {
    width: wp(22),
    height: wp(13),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(2),
  },
  textheader: {
    fontWeight: '600',
    fontSize: 12,
    color: Colors.black,
  },
  touchrec1: {
    width: wp(12),
    height: wp(12),
    alignSelf: 'center',
    top: wp(27),
    borderRadius: wp(10),
    position: 'absolute',
    backgroundColor: Colors.transperent,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.maincolor,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  touchrec: {
    width: wp(32),
    height: wp(10),
    borderRadius: wp(10),
    backgroundColor: Colors.black,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  Videoview1: {
    backgroundColor: Colors.white,
    width: wp(90),
    alignItems: 'center',
    justifyContent: 'center',
    height: wp(40),
    marginTop: wp(4),
    alignSelf: 'center',
    borderRadius: wp(2),
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
});
