import {
  heightPercentageToDP as hp,
  widthPercentageToDP as wp,
} from 'react-native-responsive-screen';

import Colors from '../../Colors';
import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  image: {
    flex: 1,
    justifyContent: 'center',
    // alignItems: 'center',
    // paddingVertical: wp(24),
  },
  innercontainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: wp(10),
  },
  viewref: {
    width: wp(10),
    height: wp(10),
    borderRadius: wp(10),
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.blue,
    alignSelf: 'flex-end',
    top: wp(4),
    right: wp(4),
  },
  ref: {
    width: wp(6),
    height: wp(6),
  },
  timerview: {
    width: wp(90),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
    marginTop: wp(2),
  },
  Videoview: {
    backgroundColor: Colors.transperentheader,
    width: wp(95),
    height: wp(60),
    alignItems: 'center',
    alignSelf: 'center',
    // borderRadius: wp(2),
    // elevation: 2,
    // shadowColor: '#000000',
    // shadowOffset: {
    //   width: 0,
    //   height: 0.5,
    // },
    // shadowRadius: 1,
    // shadowOpacity: 0.5,
  },
  reddot: {
    width: wp(3),
    height: wp(3),
    borderRadius: wp(5),
    backgroundColor: Colors.red,
    elevation: 2,
    shadowColor: Colors.red,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  texrec: {
    marginLeft: wp(2),
    fontSize: 14,
    fontWeight: '600',
    color: Colors.white,
  },
  imaginner: {
    width: wp(3),
    height: wp(3),
  },
  likview: {
    flexDirection: 'row',
    height: wp(10),
    alignItems: 'center',
    backgroundColor: Colors.transperentheader,
    // width: wp(16),
    justifyContent: 'space-between',
    paddingHorizontal: wp(2),
  },
  licktxt: {
    marginLeft: wp(1),
    fontWeight: '600',
    color: Colors.white,
    fontSize: 12,
  },
  imaginnerherart: {
    width: wp(5),
    height: wp(5),
    tintColor: Colors.red,
  },
  donttextor: {
    fontSize: 14,
    fontWeight: '400',
    color: Colors.black,
  },
  linview: {
    width: wp(40),
    backgroundColor: Colors.gray,
    height: 1,
  },
  uplodvideo: {
    borderStyle: 'dashed',
    borderWidth: 1,
    borderRadius: 1,
    borderColor: Colors.blue,
    width: wp(87),
    height: wp(37),
    alignItems: 'center',
    justifyContent: 'center',
  },
  imgup: {
    width: wp(10),
    height: wp(10),
  },
  textup: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: '600',
    marginTop: wp(2),
  },
  orview: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    width: wp(90),
    marginTop: wp(5),
    alignSelf: 'center',
  },
  recodmenuview: {
    backgroundColor: Colors.white,
    height: wp(46),
    width: wp(92),
    marginTop: wp(2),
    marginBottom: wp(4),
  },
  recoptin: {
    flexDirection: 'row',
    width: wp(90),
    height: wp(12),
    // backgroundColor: Colors.red,
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(3),
  },
  imaginner1: {
    width: wp(5),
    height: wp(5),
    tintColor: Colors.white,
  },
  imaginner2: {
    width: wp(4),
    height: wp(4),
  },
  thumbimg1: {
    height: wp(46),
    width: wp(92),
    alignSelf: 'center',
    borderBottomColor: Colors.red,
    borderBottomWidth: 3,
  },
  thumbimg: {
    height: wp(46),
    width: wp(92),
    alignSelf: 'center',
  },
  text: {
    fontSize: 14,
    color: Colors.black,
    fontWeight: '600',
    alignSelf: 'center',
    marginTop: wp(3),
    marginBottom: wp(2),
    // height: wp(8),
    textAlign: 'center',
  },
  hedview: {
    backgroundColor: Colors.transperentheader,
    width: wp(90),
    height: wp(7),
    marginTop: wp(0),
    justifyContent: 'center',
  },
  liveview: {
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(9),
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.transperent,
  },
  temodal: {
    fontSize: 12,
    color: Colors.black,
    fontWeight: '600',
  },
  temodal1: {
    fontSize: 10,
    color: Colors.black,
    fontWeight: '400',
  },
  touchmodalbu: {
    backgroundColor: Colors.black,
    width: wp(14),
    alignItems: 'center',
    justifyContent: 'center',
    height: wp(6),
    borderRadius: wp(3),
  },
  viewmobu: {
    flexDirection: 'row',
    width: wp(33),
    marginTop: wp(4),
    justifyContent: 'space-between',
    paddingHorizontal: wp(2),
  },
  textmo: {
    fontSize: 12,
    color: Colors.white,
    fontWeight: '600',
  },
  textmo1: {
    fontSize: 12,
    color: Colors.black,
    fontWeight: '600',
  },
  touchmodalbu1: {
    borderColor: Colors.black,
    backgroundColor: Colors.white,
    borderWidth: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: wp(14),
    height: wp(6),
    borderRadius: wp(3),
  },
  confmodal: {
    width: wp(70),
    height: wp(24),
    alignSelf: 'center',
    top: wp(55),
    paddingHorizontal: wp(4),
    paddingVertical: wp(4),
    borderRadius: wp(2),
    backgroundColor: Colors.white,
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  asklivtxt: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.white,
  },
  buttonview: {
    flexDirection: 'row',
    alignItems: 'center',
    width: wp(90),
    justifyContent: 'space-between',
    paddingHorizontal: wp(2),
  },
  coverrstyl: {
    width: wp(43),
    height: wp(27),
    borderRadius: wp(1),
  },
  flatviecover: {
    width: wp(90),
    height: wp(30),
    alignSelf: 'center',
  },
  coverrstylspace: {
    width: wp(45),
    height: wp(28),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(2),
  },
  textheader: {
    fontWeight: '600',
    fontSize: 12,
    color: Colors.black,
  },
  touchrecplay: {
    width: wp(12),
    height: wp(12),
    alignSelf: 'center',

    borderRadius: wp(10),

    backgroundColor: Colors.transperent,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.maincolor,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  touchrec1: {
    width: wp(12),
    height: wp(12),
    alignSelf: 'center',
    top: wp(27),
    borderRadius: wp(10),
    position: 'absolute',
    backgroundColor: Colors.transperent,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.maincolor,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  touchrec21: {
    height: wp(10),
    width: wp(92),
    backgroundColor: Colors.transperentheader,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  touchrec22: {
    height: wp(26),
    width: wp(92),
    backgroundColor: Colors.transperentheader,
    alignItems: 'center',
    justifyContent: 'center',
  },
  proimag: {
    width: wp(5),
    height: wp(5),
    borderRadius: wp(6),
  },
  sharmain: {
    flexDirection: 'row',
    width: wp(22),
    backgroundColor: Colors.transperentheader,
    height: wp(10),
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: wp(4),
  },
  proimag1: {
    width: wp(4),
    height: wp(4),
    borderRadius: wp(6),
  },
  shview: {
    width: wp(6),
    height: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.blue,
    borderRadius: wp(6),
  },
  perreponpro: {
    height: wp(10),
    width: wp(70),
    alignItems: 'center',
    paddingHorizontal: wp(2),
    backgroundColor: Colors.transperentheader,
    flexDirection: 'row',
  },
  textpro: {
    fontSize: 10,
    marginLeft: wp(2),
    color: Colors.white,
    fontWeight: '600',
  },
  touchrec23: {
    height: wp(10),
    width: wp(92),
    backgroundColor: Colors.transperentheader,
    flexDirection: 'row',
  },
  proview: {
    width: wp(6),
    height: wp(6),
    alignItems: 'center',
    justifyContent: 'center',
    borderRadius: wp(6),
    backgroundColor: Colors.white,
  },
  touchrec61: {
    height: wp(46),
    width: wp(46),
    backgroundColor: Colors.transperentheader,
  },
  viewcoment: {
    width: wp(46),
    flexDirection: 'row',
    backgroundColor: Colors.transperentheader,
    paddingHorizontal: wp(1),
    paddingVertical: wp(1),
  },
  viewspacecoment: {
    width: wp(46),
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: Colors.transperentheader,
    paddingVertical: wp(1),
  },
  touchrec62: {
    height: wp(46),
    width: wp(46),
    backgroundColor: Colors.transperent,
  },
  cros: {
    width: wp(4),
    height: wp(4),
    tintColor: Colors.gray,
  },
  flatlistview: {
    width: wp(46),
    height: wp(27),
  },
  sendchat: {
    width: wp(44),
    height: wp(8),
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    borderWidth: 1,
    borderRadius: wp(5),
    borderColor: Colors.gray,
    paddingHorizontal: wp(2),
  },
  inputstyl: {
    width: wp(35),
    height: wp(12),
    color: Colors.white,
    fontSize: 10,
    borderRadius: wp(5),
    paddingHorizontal: wp(1),
    backgroundColor: Colors.transperentheader,
  },
  coinspace: {
    width: wp(20),
    height: wp(8),
    backgroundColor: Colors.white,
  },
  txt: {
    fontSize: 10,
    color: Colors.black,
    fontWeight: '600',
    marginLeft: wp(1),
  },
  coin: {
    width: wp(20),
    height: wp(7),
    alignItems: 'center',
    // justifyContent: 'space-between',
    alignSelf: 'center',
    // paddingHorizontal: wp(2),
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: Colors.gray,
  },
  listvflat: {
    position: 'absolute',
    backgroundColor: Colors.white,
    width: wp(20),
    left: wp(60),
    top: wp(1),
    height: wp(30),
    borderRadius: wp(2),
    paddingHorizontal: wp(1),
    paddingVertical: wp(1),
  },
  sendcom: {
    width: wp(4),
    height: wp(4),
  },
  comtxtcrossview: {
    width: wp(46),
    height: wp(10),
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: wp(2),
    paddingVertical: wp(2),
  },
  comtxt: {
    fontSize: 14,
    fontWeight: '600',
    color: Colors.white,
  },
  touchrec6: {
    height: wp(42),
    width: wp(92),
    alignSelf: 'center',
    flexDirection: 'row',
    top: wp(11),
    // borderRadius: wp(10),
    position: 'absolute',
    backgroundColor: Colors.transperentheader,
    elevation: 2,
    // flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.maincolor,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  touchrec2: {
    height: wp(46),
    width: wp(92),
    alignSelf: 'center',
    top: wp(11),
    // borderRadius: wp(10),
    position: 'absolute',
    backgroundColor: Colors.transperentheader,
    elevation: 2,
    // flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.maincolor,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  touchrec: {
    width: wp(32),
    height: wp(10),
    borderRadius: wp(10),
    backgroundColor: Colors.black,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
  Videoview1: {
    backgroundColor: Colors.white,
    width: wp(90),
    alignItems: 'center',
    justifyContent: 'center',
    height: wp(40),
    marginTop: wp(4),
    alignSelf: 'center',
    borderRadius: wp(2),
    elevation: 2,
    shadowColor: '#000000',
    shadowOffset: {
      width: 0,
      height: 0.5,
    },
    shadowRadius: 1,
    shadowOpacity: 0.5,
  },
});
